[package]
name = "log_indexer_rs"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3          # Optimize for size; you can use "3" for max speed
lto = true               # Enable Link Time Optimization
codegen-units = 1        # Better optimizations by compiling as one unit
panic = "abort"          # Smaller binaries, faster panics (good if you don't need unwinding)
strip = true             # Strip debug symbols from binary

[profile.dev]
opt-level = 1            # Some optimizations for dev builds (optional)

# Optional: enable these for smaller binaries and faster runtime (at some cost of debuggability)
# debug = false
# incremental = false


[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
regex = "1"
rusqlite = { version = "0.29", features = ["bundled"] }
flate2 = "1.0"
chrono = { version = "0.4", features = ["serde"] }
