[request_definition]
r = sub, obj, ctx

[policy_definition]
p = sub, obj

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (has_role(r.ctx, p.sub)) && (p.obj == "*" || r.obj == p.obj)
